### ISSUE TITLE
EPIC_many_shot_verbs.csv not found

### ISSUE THREAD

**Issue by sourav22899** [fpv-iplab/rulstm#12]
Hi,

Thanks for the awesome work! Really clean and precise documentation.

I was trying to run the validation script for the object detection branch on the ek100 dataset when I encountered the following error:
` 
FileNotFoundError: [Errno 2] File b'data/ek100/EPIC_many_shot_verbs.csv' does not exist: b'data/ek100/EPIC_many_shot_verbs.csv'
`
Should I copy the file with the same name from `data/ek55` directory to `data/ek100` or there is a separate file? Thanks in advance!

**Comment by antoninofurnari** [comment]
Dear sourav22899,

Many thanks for rasing this issue! I have revised the code and noted a few major problems:

- The script to download the models trained on EPIC-KITCHENS-100 was not working. I have now fixed it.
- The validation code was incomplete. In particular, it had not been adapted to perform evaluations ok EPIC-KITCHENS-100 using the new official measures.

Since the code was trying to evaluate using the old measures, it required the "many_shot_verbs.csv" file. However, many shot labels are not provided with EPIC-KITCHENS-100 and those of EPIC-KITCHENS-55 do not apply. 

I have hence updated the code to perform evaluation according to the new measures and added a few new csvs to allow computation of performance on tail classes and unseen subjects.

Please try to pull the new version and add the "-ek100" parameter when validating as explained in the updated README. E.g.,

`python main.py validate data/ek100 models/ek100 --modality rgb --task anticipation --num_class 3806 --mt5r -ek100`

Hope this solves the issue. Please do let me know if there are other problems.

Best,
Antonino
