### ISSUE TITLE
About the EK55 dataset

### ISSUE THREAD

**Issue by wangxiujielalala** [fpv-iplab/rulstm#22]
Hello, I have noticed that rulstm/rulstm/data/ek55 / trainingcsv file format and rulstm/rulstm/data/ek55 test_seencsv is not the same. What is the meaning of each column of these two files? Should the two file formats be consistent? I am looking forward to your reply, which will be very helpful to my research.

**Comment by antoninofurnari** [comment]
Hello, thank you for pointing this out. I have updated the readme adding information on the format of CSV files, see below:

Training and validation CSVs report the following columns:
 * Annotation ID;
 * Video name (without extension);
 * Start frame;
 * End frame;
 * Verb ID;
 * Noun ID;
 * Action ID.
 
The test CSVs do not report the last three columns since test annotations are not public. These CSVs are provided to allow producing predicitons in JSON format to be submitted to the leaderboard.

Hope this clarifies. Please let me know if there are any other doubts.

Best
